import { Nunito } from 'next/font/google'
import { Providers } from "@/redux/provider";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const font = Nunito({ 
  subsets: ['latin'], 
});

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
     <body className={font.className}>
     <UserProvider>
        <div className="bg-gray-300 min-h-screen pb-20 pt-28">
          <Providers>
            <Navbar/>
            {children}
          </Providers>
        </div>
        </UserProvider>
      </body>
    </html>
  );
        
}